name: Draft PDF
on:
  push:
    paths:
      - 'paper/paper.md'
      - 'paper/paper.bib'
      - 'paper/images/**'
      - '.github/workflows/draft-pdf.yml'
    paths-ignore:
      - 'paper/paper.pdf'  # Explicitly ignore PDF changes

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PDF_COMMIT_TOKEN }}
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '[skip ci] (auto) Paper PDF Draft'
          add: 'paper/paper.pdf'
          token: ${{ secrets.PDF_COMMIT_TOKEN }}
